# Analysis of Variance (ANOVA)
- 

In [1]:
import numpy as np

In [16]:
data = np.array([
                [7, 9, 5, 8, 6, 8, 6, 10, 7, 4],
                [4, 3, 6, 2, 7, 5, 5, 4, 1, 3],
                [6, 1, 3, 5, 3, 4, 6, 4, 7, 3]]                
                )
np.shape(data)

brands = np.array([
    [194, 189, 185, 183, 195],
    [184, 204, 183, 193, 197],
    [189, 190, 186, 184, 194],
    [189, 190, 183, 186, 202],
    [188, 189, 179, 194, 200],
    [186, 207, 191, 199, 211],
    [195, 203, 188, 196, 203],
    [186, 193, 196, 188, 206],
    [183, 181, 189, 193, 202],
    [188, 206, 194, 196, 195]
    ])
brands_T = brands.T
print(np.shape(brands_T), brands_T)

(5, 10) [[194 184 189 189 188 186 195 186 183 188]
 [189 204 190 190 189 207 203 193 181 206]
 [185 183 186 183 179 191 188 196 189 194]
 [183 193 184 186 194 199 196 188 193 196]
 [195 197 194 202 200 211 203 206 202 195]]


# Calculate the Separate Sample Mean

In [17]:
each_distribution_mean = []

def separate_sample_mean(distributions):

    for row in range(len(distributions)):
        each_distribution_mean.append(np.mean(distributions[row]))

    return each_distribution_mean

def grand_mean(ssm):
    
    return round(np.mean(ssm), 1)

In [18]:
ssm = separate_sample_mean(brands_T)
ssm

[188.2, 195.2, 187.4, 191.2, 200.5]

In [19]:
gm = grand_mean(ssm)
gm

192.5

---

# Calculate the Sum of Squares Between Distributions

- When looking at multiple distributions, what's the spread between them?
- Analogy : 3 people - LA, Simmons, and Me along with the size of our estate (the latter to get a mean; mean of our estate (avg size/spread of our estate) is represented by name_mean); Here, we will calculate : 
    - What's the spread between LA and Simmons?
    - What's the spread between LA and Me?
    - What's the spread between Simmmons and Me?
- To calculate :
    - Mean of each distribution (ed) : la_mean, simmons_mean, my_mean **$\rightarrow$ 3 different scalars**
    - Grand mean (gm) : np.mean(ed) = la_mean + simmons_mean + my_mean / 3 **$\rightarrow$ 1 scalar**
    - Square gm (sgm) : (ed - gm)^2 = (la_mean - gm)^2 + (simmons_mean)^2 + (my_mean - gm)^2 **$\rightarrow$ 3 different scalars**
    - #distributions (n)
    - ss_between (ssb) = (n * sgm) = n * (la_mean - gm)^2 + n * (simmons_mean)^2 + n * (my_mean - gm)^2 **$\rightarrow$ 1 scalar**

In [20]:
def calc_ss_between(n, x_i, x_g):

    ssb = np.sum(np.multiply(n, np.square(x_i - x_g)))
    
    return ssb

In [21]:
calc_ss_between(10, ssm, gm)

1174.8000000000002

---

# Calculate the Sum of Squares Within a Single Distribution for Each Distribution

- When looking at each distribution alone, what's the spread within it?
- The larger the spread between each distribution $\Rightarrow$ the larger the spead between each distribution (ssm between)

In [ ]:
def calc_ss_within(n, )