# VOO

- Source: [Vanguard 500 Index Fund (VOO)](https://finance.yahoo.com/quote/VOO/history?p=VOO)
- [ ] The source has dividend on certain days. Be sure to remove.

# Imports + Load Data

In [1]:
import pandas as pd

In [2]:
BASE = '/Users/brinkley97/Documents/development/'
DATASETS = 'applied_time_series_and_machine_learning/datasets/yahoo_finance/'

In [3]:
VOO_DAILY_FILE = BASE + DATASETS + 'VOO_DAILY_06-02-23_TO_06-06-22.csv'

In [4]:
def load_data(file):
    
    original_data = pd.read_csv(file)
    copy_of_data = original_data.copy()
    
    return copy_of_data

# Preprocessing

## Multivariate Time Series of VOO

In [5]:
voo_daily_df = load_data(VOO_DAILY_FILE)
voo_daily_df

Date        Open        High         Low       Close   Adj Close  \
0    2022-06-06  381.329987  382.959991  377.410004  378.470001  371.954468   
1    2022-06-07  375.160004  382.609985  374.709991  382.170013  375.590790   
2    2022-06-08  380.500000  382.230011  377.260010  377.989990  371.482727   
3    2022-06-09  376.239990  378.440002  369.019989  369.100006  362.745789   
4    2022-06-10  362.929993  363.690002  358.230011  358.269989  352.102234   
..          ...         ...         ...         ...         ...         ...   
245  2023-05-26  381.640015  386.570007  381.540009  385.869995  385.869995   
246  2023-05-30  387.760010  388.260010  384.760010  385.989990  385.989990   
247  2023-05-31  384.309998  385.160004  382.420013  383.890015  383.890015   
248  2023-06-01  384.200012  388.570007  382.970001  387.570007  387.570007   
249  2023-06-02  390.079987  393.959991  389.540009  393.260010  393.260010   

      Volume  
0    2659500  
1    2649900  
2    3436400  
3    3022000  
4    7629700  
..       ...  
245  3042800  
246  3968500  
247  4205300  
248  3563600  
249  7365800  

[250 rows x 7 columns]

## Univariate Time Series of VOO

In [6]:
open_train_df = voo_daily_df.loc[:, 'Open']
open_train_df

0      381.329987
1      375.160004
2      380.500000
3      376.239990
4      362.929993
          ...    
245    381.640015
246    387.760010
247    384.309998
248    384.200012
249    390.079987
Name: Open, Length: 250, dtype: float64

In [7]:
PATH_TO_BOOK = 'book-intro_to_tsf_with_python/'
TS_AS_SML_FILE = BASE + PATH_TO_BOOK + '3-timeSeriesAsSupervisedLearning.ipynb'

In [8]:
# %load TS_AS_SML_FILE
# /Users/brinkley97/Documents/development/book-intro_to_tsf_with_python/3-timeSeriesAsSupervisedLearning.ipynb

In [9]:
%run $TS_AS_SML_FILE

Input Univariate Time Series:
[ 1  2  3  4  5  6  7  8  9 10] 
X of size (10,)

Univariate Time Series as Supervised Machine Learning:
[1 2 3] 4
[2 3 4] 5
[3 4 5] 6
[4 5 6] 7
[5 6 7] 8
[6 7 8] 9
[7 8 9] 10
X of size (7, 3)
y of size (7,)
     0    0    0   0     0
0  NaN  NaN  NaN   1   2.0
1  NaN  NaN  1.0   2   3.0
2  NaN  1.0  2.0   3   4.0
3  1.0  2.0  3.0   4   5.0
4  2.0  3.0  4.0   5   6.0
5  3.0  4.0  5.0   6   7.0
6  4.0  5.0  6.0   7   8.0
7  5.0  6.0  7.0   8   9.0
8  6.0  7.0  8.0   9  10.0
9  7.0  8.0  9.0  10   NaN
Input Univariate Time Series:
[10, 20, 30, 40, 50, 60, 70, 80, 90] 
X of size (9,)

Univariate Time Series as Supervised Machine Learning:
X_train: 
     t-3   t-2   t-1
3  10.0  20.0  30.0
4  20.0  30.0  40.0
5  30.0  40.0  50.0
6  40.0  50.0  60.0
7  50.0  60.0  70.0
y_train: 
     t   t+1
3  40  50.0
4  50  60.0
5  60  70.0
6  70  80.0
7  80  90.0


In [10]:
MLP_FILE = BASE + PATH_TO_BOOK + 'mlpUnivariateModel.ipynb'

In [11]:
%run $MLP_FILE

2023-06-07 14:39:07.109271: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Input Univariate Time Series:
[ 1  2  3  4  5  6  7  8  9 10] 
X of size (10,)

Univariate Time Series as Supervised Machine Learning:
[1 2 3] 4
[2 3 4] 5
[3 4 5] 6
[4 5 6] 7
[5 6 7] 8
[6 7 8] 9
[7 8 9] 10
X of size (7, 3)
y of size (7,)
     0    0    0   0     0
0  NaN  NaN  NaN   1   2.0
1  NaN  NaN  1.0   2   3.0
2  NaN  1.0  2.0   3   4.0
3  1.0  2.0  3.0   4   5.0
4  2.0  3.0  4.0   5   6.0
5  3.0  4.0  5.0   6   7.0
6  4.0  5.0  6.0   7   8.0
7  5.0  6.0  7.0   8   9.0
8  6.0  7.0  8.0   9  10.0
9  7.0  8.0  9.0  10   NaN
Input Univariate Time Series:
[10, 20, 30, 40, 50, 60, 70, 80, 90] 
X of size (9,)

Univariate Time Series as Supervised Machine Learning:
X_train: 
     t-3   t-2   t-1
3  10.0  20.0  30.0
4  20.0  30.0  40.0
5  30.0  40.0  50.0
6  40.0  50.0  60.0
7  50.0  60.0  70.0
y_train: 
     t   t+1
3  40  50.0
4  50  60.0
5  60  70.0
6  70  80.0
7  80  90.0
Input Univariate Time Series:
[10, 20, 30, 40, 50, 60, 70, 80, 90] 
X of size (9,)

Univariate Time Series as Su

2023-06-07 14:39:09.759184: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


[[70. 80. 90.]]

TRUE Y LABEL @ 0  =  100
PREDICTED Y LABEL @ 0  =  103.89724731445312

TRUE Y LABEL @ 1  =  110
PREDICTED Y LABEL @ 1  =  116.15861511230469

ERROR =  5.153497682716068


In [12]:
univariate_time_series = open_train_df.values
# univariate_time_series = np.flip(univariate_time_series)
# univariate_time_series

## Univariate Time Series of VOO to Supervised Machine Learning

### Univariate Unistep Model

#### Split Data

In [13]:
prior_observations, forecasting_step = [3, 1]
X_train_df, y_train_df, X_y_df = convert_uts_sequence_to_sml_with_pd(univariate_time_series, prior_observations, forecasting_step) 

Input Univariate Time Series:
[381.329987 375.160004 380.5      376.23999  362.929993 349.109985
 346.369995 346.820007 340.480011 337.309998 343.190002 342.079987
 347.630005 352.029999 361.       360.079987 350.429993 345.880005
 346.160004 345.480011 351.230011 354.01001  355.910004 354.839996
 352.600006 344.73999  343.410004 351.730011 356.970001 354.950012
 360.700012 362.359985 366.690002 363.839996 362.119995 362.48999
 369.420013 374.730011 376.119995 376.109985 377.190002 380.880005
 376.649994 381.779999 379.019989 384.98999  388.869995 387.950012
 390.48999  393.23999  391.559998 392.420013 390.700012 383.429993
 379.559998 378.899994 381.76001  385.549988 369.769989 371.299988
 367.609985 361.100006 367.950012 361.359985 358.859985 363.380005
 370.23999  375.820007 369.339996 362.579987 361.160004 354.559998
 352.799988 355.380005 356.380005 347.549988 342.079987 338.230011
 339.790009 334.799988 337.149994 332.570007 331.790009 342.140015
 343.119995 345.179993 339.079987

In [14]:
X_train_values, y_train_values, X_y_values = get_x_y_training_values(X_train_df, y_train_df, X_y_df, forecasting_step)

In [15]:
X_train_values

array([[381.329987, 375.160004, 380.5     ],
       [375.160004, 380.5     , 376.23999 ],
       [380.5     , 376.23999 , 362.929993],
       [376.23999 , 362.929993, 349.109985],
       [362.929993, 349.109985, 346.369995],
       [349.109985, 346.369995, 346.820007],
       [346.369995, 346.820007, 340.480011],
       [346.820007, 340.480011, 337.309998],
       [340.480011, 337.309998, 343.190002],
       [337.309998, 343.190002, 342.079987],
       [343.190002, 342.079987, 347.630005],
       [342.079987, 347.630005, 352.029999],
       [347.630005, 352.029999, 361.      ],
       [352.029999, 361.      , 360.079987],
       [361.      , 360.079987, 350.429993],
       [360.079987, 350.429993, 345.880005],
       [350.429993, 345.880005, 346.160004],
       [345.880005, 346.160004, 345.480011],
       [346.160004, 345.480011, 351.230011],
       [345.480011, 351.230011, 354.01001 ],
       [351.230011, 354.01001 , 355.910004],
       [354.01001 , 355.910004, 354.839996],
       [35

In [16]:
y_train_values

array([[376.23999 ],
       [362.929993],
       [349.109985],
       [346.369995],
       [346.820007],
       [340.480011],
       [337.309998],
       [343.190002],
       [342.079987],
       [347.630005],
       [352.029999],
       [361.      ],
       [360.079987],
       [350.429993],
       [345.880005],
       [346.160004],
       [345.480011],
       [351.230011],
       [354.01001 ],
       [355.910004],
       [354.839996],
       [352.600006],
       [344.73999 ],
       [343.410004],
       [351.730011],
       [356.970001],
       [354.950012],
       [360.700012],
       [362.359985],
       [366.690002],
       [363.839996],
       [362.119995],
       [362.48999 ],
       [369.420013],
       [374.730011],
       [376.119995],
       [376.109985],
       [377.190002],
       [380.880005],
       [376.649994],
       [381.779999],
       [379.019989],
       [384.98999 ],
       [388.869995],
       [387.950012],
       [390.48999 ],
       [393.23999 ],
       [391.5

In [17]:
X_y_values

array([[384.309998, 384.200012, 390.079987]])

In [19]:
ytrue = [393.54]
univariate_mlp_model(X_train_values, y_train_values, X_y_values, ytrue, prior_observations, forecasting_step)

[[384.309998 384.200012 390.079987]]

TRUE Y LABEL @ 0  =  393.54
PREDICTED Y LABEL @ 0  =  388.670166015625

ERROR =  4.8698339843750205


4.8698339843750205

# Univariate Multistep Model

In [20]:
prior_observations, forecasting_step = [3, 3]
X_train_df, y_train_df, X_y_df = convert_uts_sequence_to_sml_with_pd(univariate_time_series, prior_observations, forecasting_step) 

Input Univariate Time Series:
[381.329987 375.160004 380.5      376.23999  362.929993 349.109985
 346.369995 346.820007 340.480011 337.309998 343.190002 342.079987
 347.630005 352.029999 361.       360.079987 350.429993 345.880005
 346.160004 345.480011 351.230011 354.01001  355.910004 354.839996
 352.600006 344.73999  343.410004 351.730011 356.970001 354.950012
 360.700012 362.359985 366.690002 363.839996 362.119995 362.48999
 369.420013 374.730011 376.119995 376.109985 377.190002 380.880005
 376.649994 381.779999 379.019989 384.98999  388.869995 387.950012
 390.48999  393.23999  391.559998 392.420013 390.700012 383.429993
 379.559998 378.899994 381.76001  385.549988 369.769989 371.299988
 367.609985 361.100006 367.950012 361.359985 358.859985 363.380005
 370.23999  375.820007 369.339996 362.579987 361.160004 354.559998
 352.799988 355.380005 356.380005 347.549988 342.079987 338.230011
 339.790009 334.799988 337.149994 332.570007 331.790009 342.140015
 343.119995 345.179993 339.079987

In [21]:
X_train_values, y_train_values, X_y_values = get_x_y_training_values(X_train_df, y_train_df, X_y_df, forecasting_step)

In [22]:
X_train_values

array([[381.329987, 375.160004, 380.5     ],
       [375.160004, 380.5     , 376.23999 ],
       [380.5     , 376.23999 , 362.929993],
       [376.23999 , 362.929993, 349.109985],
       [362.929993, 349.109985, 346.369995],
       [349.109985, 346.369995, 346.820007],
       [346.369995, 346.820007, 340.480011],
       [346.820007, 340.480011, 337.309998],
       [340.480011, 337.309998, 343.190002],
       [337.309998, 343.190002, 342.079987],
       [343.190002, 342.079987, 347.630005],
       [342.079987, 347.630005, 352.029999],
       [347.630005, 352.029999, 361.      ],
       [352.029999, 361.      , 360.079987],
       [361.      , 360.079987, 350.429993],
       [360.079987, 350.429993, 345.880005],
       [350.429993, 345.880005, 346.160004],
       [345.880005, 346.160004, 345.480011],
       [346.160004, 345.480011, 351.230011],
       [345.480011, 351.230011, 354.01001 ],
       [351.230011, 354.01001 , 355.910004],
       [354.01001 , 355.910004, 354.839996],
       [35

In [23]:
y_train_values

array([[376.23999 , 362.929993, 349.109985],
       [362.929993, 349.109985, 346.369995],
       [349.109985, 346.369995, 346.820007],
       [346.369995, 346.820007, 340.480011],
       [346.820007, 340.480011, 337.309998],
       [340.480011, 337.309998, 343.190002],
       [337.309998, 343.190002, 342.079987],
       [343.190002, 342.079987, 347.630005],
       [342.079987, 347.630005, 352.029999],
       [347.630005, 352.029999, 361.      ],
       [352.029999, 361.      , 360.079987],
       [361.      , 360.079987, 350.429993],
       [360.079987, 350.429993, 345.880005],
       [350.429993, 345.880005, 346.160004],
       [345.880005, 346.160004, 345.480011],
       [346.160004, 345.480011, 351.230011],
       [345.480011, 351.230011, 354.01001 ],
       [351.230011, 354.01001 , 355.910004],
       [354.01001 , 355.910004, 354.839996],
       [355.910004, 354.839996, 352.600006],
       [354.839996, 352.600006, 344.73999 ],
       [352.600006, 344.73999 , 343.410004],
       [34

In [24]:
X_y_values

array([[384.309998, 384.200012, 390.079987]])

In [25]:
ytrue = [393.54, 392.05, 393.67]
univariate_mlp_model(X_train_values, y_train_values, X_y_values, ytrue, prior_observations, forecasting_step)

[[384.309998 384.200012 390.079987]]

TRUE Y LABEL @ 0  =  393.54
PREDICTED Y LABEL @ 0  =  390.67742919921875

TRUE Y LABEL @ 1  =  392.05
PREDICTED Y LABEL @ 1  =  390.3476257324219

TRUE Y LABEL @ 2  =  393.67
PREDICTED Y LABEL @ 2  =  388.7140808105469

ERROR =  3.4473915138254703


3.4473915138254703